class ConfigVars:
    _total = _executed = 0
    _pass = _fail = 0
    _skip = _error = 0
    _xpass = _xfail = 0
    _apass = _afail = 0
    _askip = _aerror = 0
    _axpass = _axfail = 0
    _astotal = 0
    _aspass = 0
    _asfail = 0
    _asskip = 0
    _aserror = 0
    _asxpass = 0
    _asxfail = 0
    _asrerun = 0
    _current_error = ""
    _suite_name = None
    _test_name = None
    _test_suite_name = []
    _test_pass_list = []
    _test_fail_list = []
    _test_skip_list = []
    _test_xpass_list = []
    _test_xfail_list = []
    _test_error_list = []
    _test_status = None
    _start_execution_time = 0
    _execution_time = _duration = 0
    _test_metrics_content = ""
    _test_logs_content = ""
    _logs_notice = ""
    _suite_metrics_content = ""
    _previous_suite_name = "None"
    _initial_trigger = True
    _spass_tests = 0
    _sfail_tests = 0
    _sskip_tests = 0
    _serror_tests = 0
    _srerun_tests = 0
    _sxfail_tests = 0
    _sxpass_tests = 0
    _suite_length = 0
    _archive_tab_content = ""
    _archive_body_content = ""
    _archive_count = ""
    archive_pass = 0
    archive_fail = 0
    archive_skip = 0
    archive_xpass = 0
    archive_xfail = 0
    archive_error = 0
    archives = {}
    highlights = {}
    p_highlights = {}
    max_failure_suite_name = ''
    max_failure_suite_name_final = ''
    max_failure_suite_count = 0
    similar_max_failure_suite_count = 0
    max_failure_total_tests = 0
    max_failure_percent = ''
    trends_label = []
    tpass = []
    tfail = []
    tskip = []
    _suite_error = 0
    _suite_fail = 0
    screen_base = ''
    screen_img = None
    _attach_screenshot_details = ''
    _attachments = []
    _attachment_items = ''
    _attachment_store = ''
    _environment_rows = ''
    _environment = ''
    _environment_label = ''
    _environment_class = ''
    _coverage = None
    _coverage_state = 'is-empty'
    _coverage_rows = ''
    _coverage_tiles = ''
    _coverage_chip = ''
    _coverage_display = '0'
    _coverage_dash = ''
    _coverage_grade = 'low'
    _coverage_meta = ''
    _coverage_delta = ''
    _coverage_delta_class = ''
    _coverage_target = ''
    _coverage_link = ''
    _coverage_note = ''
    _coverage_notice = ''
    _coverage_branch = 'false'
    _coverage_trend_labels = '[]'
    _coverage_trend_values = '[]'
    _coverage_trend_state = 'no-trend'
    tcoverage = []
    _report_links = ''
    _title = 'PYTEST REPORT'
    _title_full = 'PYTEST REPORT'
    _title_class = ''